#ifndef CONFIG_H
#define CONFIG_H

// Firmware Configuration
// FIRMWARE_VERSION is auto-generated by version_inject.py during build
// FIRMWARE_ALGORITHM is auto-generated by version_inject.py during build
#define FIRMWARE_TLS 0  // Set to 1 for HTTPS, 0 for HTTP

// OTA Server URLs
#if FIRMWARE_TLS == 1
#define MANIFEST_URL "https://ota.sinaungoding.com:8443/api/v1/firmware/manifest.json"
#define FIRMWARE_URL "https://ota.sinaungoding.com:8443/api/v1/firmware/firmware-otaq.bin"
#else
#define MANIFEST_URL "http://broker.sinaungoding.com:8000/api/v1/firmware/manifest.json"
#define FIRMWARE_URL "http://broker.sinaungoding.com:8000/api/v1/firmware/firmware-otaq.bin"
#endif

// WiFi Configuration
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define WIFI_CONNECT_TIMEOUT 30  // seconds

// MQTT Configuration
#if FIRMWARE_TLS == 1
#define MQTT_SERVER "ota.sinaungoding.com"
#define MQTT_PORT 8883
#define MQTT_USER "uwais"
#define MQTT_PASS "uw415_4Lqarn1"
#else
#define MQTT_SERVER "broker.sinaungoding.com"
#define MQTT_PORT 1884
#define MQTT_USER "noureen"
#define MQTT_PASS "1234"
#endif

#define MQTT_TOPIC_OTA "device/002/ota/update"
#define MQTT_TOPIC_METRICS "ota/metrics"
#define MQTT_TOPIC_CPU "ota/cpu"
#define MQTT_RECONNECT_INTERVAL 5000  // ms

// NTP Configuration
#define NTP_SERVER1 "pool.ntp.org"
#define NTP_SERVER2 "time.nist.gov"
#define NTP_SERVER3 "time.google.com"
#define NTP_TIMEZONE "JST-9"  // Change to "WIB-7" for Indonesia, "UTC0" for UTC
#define NTP_SYNC_TIMEOUT 15  // seconds

// OTA Configuration
#define OTA_CHECK_INTERVAL 300000  // ms (5 minutes)
#define OTA_DOWNLOAD_BUFFER 512  // bytes

// ED25519 Public Key (32 bytes in hex format - 64 hex characters)
#define PUBLIC_KEY_HEX "0000000000000000000000000000000000000000000000000000000000000000"

// Status Update Interval
#define STATUS_UPDATE_INTERVAL 30000  // ms

#endif // CONFIG_H
