#ifndef CONFIG_H
#define CONFIG_H

// Firmware Configuration
// FIRMWARE_VERSION is auto-generated by version_inject.py during build
// FIRMWARE_ALGORITHM is auto-generated by version_inject.py during build
#define FIRMWARE_TLS 1  // Set to 1 for HTTPS, 0 for HTTP

// OTA Server URLs
#if FIRMWARE_TLS == 1
#define MANIFEST_URL "https://ota.sinaungoding.com:8443/api/v1/firmware/manifest.json"
#define FIRMWARE_URL "https://ota.sinaungoding.com:8443/api/v1/firmware/firmware-otaq.bin"
#else
#define MANIFEST_URL "http://broker.sinaungoding.com:8000/api/v1/firmware/manifest.json"
#define FIRMWARE_URL "http://broker.sinaungoding.com:8000/api/v1/firmware/firmware-otaq.bin"
#endif

// WiFi Configuration
#define WIFI_SSID "Laatahdhob"
#define WIFI_PASSWORD "janganmar4h"
#define WIFI_CONNECT_TIMEOUT 30  // seconds

// MQTT Configuration
// TLS Note: When FIRMWARE_TLS=1, MQTT uses secure connection (MQTTS) with CA verification
// CA certificate is stored in mqtt_handler.cpp (caCertStr)
// 
// Get your server's CA certificate:
//   openssl s_client -connect ota.sinaungoding.com:8883 -showcerts
// Or if using Let's Encrypt, use their root CA:
//   https://letsencrypt.org/certificates/
// 
// Update the CA cert in mqtt_handler.cpp for your specific server
#if FIRMWARE_TLS == 1
#define MQTT_SERVER "ota.sinaungoding.com"
#define MQTT_PORT 8883
#define MQTT_USER "uwais"
#define MQTT_PASS "uw415_4Lqarn1"
#else
#define MQTT_SERVER "broker.sinaungoding.com"
#define MQTT_PORT 1884
#define MQTT_USER "noureen"
#define MQTT_PASS "1234"
#endif

#define MQTT_TOPIC_OTA "device/002/ota/update"
#define MQTT_TOPIC_METRICS "ota/metrics"
#define MQTT_TOPIC_CPU "ota/cpu"
#define MQTT_RECONNECT_INTERVAL 5000  // ms

// NTP Configuration
#define NTP_SERVER1 "pool.ntp.org"
#define NTP_SERVER2 "time.nist.gov"
#define NTP_SERVER3 "time.google.com"
#define NTP_TIMEZONE "JST-9"  // Change to "WIB-7" for Indonesia, "UTC0" for UTC
#define NTP_SYNC_TIMEOUT 15  // seconds

// OTA Configuration
#define OTA_CHECK_INTERVAL 300000  // ms (5 minutes)
#define OTA_DOWNLOAD_BUFFER 512  // bytes

// ECDSA-SHA256-P256 Public Key (64 bytes = 128 hex characters, no spaces, no 0x prefix)
// Algorithm: ECDSA signature with SHA-256 hash and P-256 curve (secp256r1)
// Format: Pure hex string (X coordinate + Y coordinate, uncompressed)
// Private key (32 bytes): a059515a2bd9bb7473d4952fde93253609f07658cbaec5c0b77e6dc1501d5b4c
// Store private key in GitHub Secrets as ECDSA_PRIVATE_KEY_HEX
#define PUBLIC_KEY_HEX "2a1bef8f639b59b6e62ce51c0117c751255c84c346913cce94bb488c7ef212ca76961e555d9190f67b01d53cdbdafd7075001e78e64e0427017e7fb8829d3f5d"

// TLS/SSL Certificates
// CA certificates for MQTT and OTA are stored in certificates.h
// Edit src/certificates.h to update CA certificates

// Status Update Interval
#define STATUS_UPDATE_INTERVAL 30000  // ms

#endif // CONFIG_H
